title: Yaoyao Liu
affiliation: MPI for Informatics
email: yaoyao.liu (at) mpi-inf.mpg.de
google_scholar: https://scholar.google.com/citations?user=Uf9GqRsAAAAJ
github_link: https://github.com/yaoyao-liu/minimal-academic
linkedin: https://www.linkedin.com/in/liuyaoyao/
avatar: https://yyliu.net/images/avatar.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Yaoyao Liu is a Ph.D. student in computer science. His research lies in few-shot learning, meta learning, continual learning, and image generation.
canonical: https://mpi-inf.mpg.de/~yaliu/
remote_theme: yaoyao-liu/minimal-academic
